# Generated by Django 5.0.6 on 2024-05-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=255)),
                ('src', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('alt', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('permalink', models.URLField()),
                ('date_created', models.DateTimeField()),
                ('date_created_gmt', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('date_modified_gmt', models.DateTimeField()),
                ('type', models.CharField(choices=[('external', 'External'), ('internal', 'Internal')], max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('publish', 'Publish')], max_length=100)),
                ('featured', models.BooleanField()),
                ('catalog_visibility', models.CharField(choices=[('visible', 'Visible'), ('catalog', 'Catalog'), ('search', 'Search'), ('hidden', 'Hidden')], max_length=100)),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_on_sale_from', models.DateTimeField(blank=True, null=True)),
                ('date_on_sale_from_gmt', models.DateTimeField(blank=True, null=True)),
                ('date_on_sale_to', models.DateTimeField(blank=True, null=True)),
                ('date_on_sale_to_gmt', models.DateTimeField(blank=True, null=True)),
                ('on_sale', models.BooleanField()),
                ('purchasable', models.BooleanField()),
                ('total_sales', models.IntegerField()),
                ('virtual', models.BooleanField()),
                ('downloadable', models.BooleanField()),
                ('download_limit', models.IntegerField()),
                ('download_expiry', models.IntegerField()),
                ('external_url', models.URLField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_status', models.CharField(choices=[('taxable', 'Taxable'), ('none', 'None')], max_length=100)),
                ('tax_class', models.CharField(blank=True, max_length=100, null=True)),
                ('manage_stock', models.BooleanField()),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('backorders', models.CharField(choices=[('no', 'No'), ('notify', 'Notify'), ('yes', 'Yes')], max_length=100)),
                ('backorders_allowed', models.BooleanField()),
                ('backordered', models.BooleanField()),
                ('low_stock_amount', models.IntegerField(blank=True, null=True)),
                ('sold_individually', models.BooleanField()),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_required', models.BooleanField()),
                ('shipping_taxable', models.BooleanField()),
                ('shipping_class', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_class_id', models.IntegerField(blank=True, null=True)),
                ('reviews_allowed', models.BooleanField()),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('rating_count', models.IntegerField()),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('purchase_note', models.TextField(blank=True, null=True)),
                ('menu_order', models.IntegerField(blank=True, null=True)),
                ('price_html', models.TextField(blank=True, null=True)),
                ('stock_status', models.CharField(choices=[('instock', 'In stock'), ('outofstock', 'Out of stock'), ('onbackorder', 'On backorder')], max_length=100)),
                ('has_options', models.BooleanField()),
                ('post_password', models.CharField(blank=True, max_length=100, null=True)),
                ('wpcom_is_markdown', models.BooleanField()),
                ('categories', models.ManyToManyField(related_name='products', to='ecommerce.category')),
                ('images', models.ManyToManyField(related_name='products', to='ecommerce.image')),
                ('tags', models.ManyToManyField(related_name='products', to='ecommerce.tag')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
